name: essentials
description: What i need to start a project
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  flutter_cupertino_localizations: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+3
  gettext: ^1.1.0+2
  provider: ^4.0.4
  location: ^2.5.4
  http: ^0.12.0+4
  rxdart: ^0.23.1
  flutter_local_notifications: ^1.2.2
  background_fetch: ^0.5.1
  sqflite: ^1.3.0
  fl_chart: ^0.8.7
  path_provider: ^1.5.1
  path: ^1.6.4
  pin_view: ^1.0.1
  firebase_auth: ^0.15.4
  firebase_core: ^0.4.4
  firebase_messaging: ^6.0.13
  firebase_database: ^3.1.1
  firebase_analytics: ^5.0.11
  introduction_screen: ^1.0.8
  package_info: ^0.4.0+16
  install_plugin: ^2.0.1
  permission_handler: ^4.0.0
  dio: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
